Morningstar/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.views.generic.base import TemplateView
from django.contrib.sitemaps.views import sitemap
from django.views.decorators.cache import cache_page
from rest_framework import routers
from rest_framework.documentation import include_docs_urls

from Morningstar.settings.common import CACHE_TIMEOUT
from Morningstar.settings.common import MEDIA_ROOT

from .views import dev, info, shortcut, tool
from .sitemaps import Sitemaps

router = routers.DefaultRouter()


infoUrls = [
    path("favicon.ico", cache_page(CACHE_TIMEOUT)(info.get_favicon), name="favicon"),
    path("qrcode/", cache_page(CACHE_TIMEOUT)(info.get_qrcode), name="qrcode"),
    path("me/", cache_page(CACHE_TIMEOUT)(info.me), name="me"),
    path("credits/", cache_page(CACHE_TIMEOUT)(info.credits), name="credits"),
    path(
        "sitemap.xml",
        cache_page(CACHE_TIMEOUT)(sitemap),
        {"sitemaps": Sitemaps},
        name="sitemap",
    ),
    path("dev/", dev.index, name="dev_index"),
    path(
        "shortcut/<slug:name>/",
        cache_page(CACHE_TIMEOUT)(shortcut.shortcut),
        name="shortcut",
    ),
    path(
        "robots.txt",
        cache_page(CACHE_TIMEOUT)(
            TemplateView.as_view(
                template_name="base/robots.txt", content_type="text/plain"
            )
        ),
    ),
]

authUrls = [
    path("get-image-captcha/", tool.get_image_captcha, name="get_image_captcha"),
    path("activate-by-email/", tool.activate_by_email, name="activate_by_email"),
    path(
        "send-phone-code/<slug:template>/", tool.send_phone_code, name="send_phone_code"
    ),
    path(
        "send-email-code/<slug:template>/", tool.send_email_code, name="send_email_code"
    ),
    path(
        "get-login-token/<slug:identity>/", tool.get_login_token, name="get_login_token"
    ),
    path("login-by-token/<str:token>/", tool.login_by_token, name="login_by_token"),
]


urlpatterns = (
    infoUrls
    + authUrls
    + [
        path("", include("blog.urls")),
        path("api/joke/", include("joke.urls")),
        path("lover/", include("lover.urls")),
        path("nav/", include("nav.urls")),
        path("proxy/", include("proxy.urls")),
        path("api/recognizer/", include("recognizer.urls")),
        path("rss/", include("rss.urls")),
        path("api/share/", include("share.urls")),
        # 调试
        path("debug/", include("debug_toolbar.urls")),
        # 媒体
        re_path(r"media/(?P<path>.*)$", serve, {"document_root": MEDIA_ROOT}),
        # 管理
        path("admin/", admin.site.urls, name="admin"),
        # restful api
        # path("api/", include(router.urls)), # TODO: 未来需要更规范的使用
        path("docs/", include_docs_urls(title="API文档", description="hiahiahia")),
    ]
)

apps/blog/urls.py
from django.urls import path
from django.urls import include
from Morningstar.settings.common import CACHE_TIMEOUT
from django.views.decorators.cache import cache_page

from . import feeds
from . import views

app_name = "blog"
urlpatterns = [
    path("contact/", views.contact, name="contact"),
    path("search/", views.BlogSearchView(), name="search"),
    path("feed/", cache_page(CACHE_TIMEOUT)(feeds.AllPostsRssFeed()), name="feed"),
    path("", views.IndexView.as_view(), name="index"),
    path("posts/<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path(
        "archives/<int:year>/<int:month>/", views.ArchiveView.as_view(), name="archive"
    ),
    path("categories/<int:pk>/", views.CategoryView.as_view(), name="category"),
    path("tags/<int:pk>/", views.TagView.as_view(), name="tag"),
    path("comment/<int:post_pk>", views.comment, name="comment"),
    path("thumbs/", views.thumbs, name="thumbs"),
    # 账号相关
    path("logout/", views.logout, name="logout"),
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("updateInfo/", views.updateInfo, name="updateInfo"),
    path("updatePassword/", views.updatePassword, name="updatePassword"),
    path("updateEmail/", views.updateEmail, name="updateEmail"),
    path("updatePhone/", views.updatePhone, name="updatePhone"),
]

apps/nav/urls.py
from django.urls import path
from Morningstar.settings.common import CACHE_TIMEOUT
from django.views.decorators.cache import cache_page
from . import views

app_name = "nav"
urlpatterns = [
    path("", views.index, name="index"),
]

apps/nav/views.py
from django.shortcuts import render
from django.http import HttpRequest
from django.contrib.auth.decorators import login_required
import json
from Morningstar.settings.common import MEDIA_ROOT

JSON_FILE = MEDIA_ROOT / "nav/data.json"


def __get_data(json_file):
    with open(json_file) as f:
        data = dict(json.load(f))
    return data


def index(request: HttpRequest):
    data = __get_data(JSON_FILE)
    categories: list[dict] = data["categories"]
    if not request.user.is_superuser:
        for category in categories:
            if category.get("level") == "admin":
                categories.remove(category)
    return render(request, "nav/index.html", context={"categories": categories})

apps/nav/templates/nav/index.html
{% load compress %}
{% load matomo_tags %}
{% load static %}
{% load nav_extras %}
<!DOCTYPE html>
<html lang="zh-CN" data-theme="light">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<meta http-equiv="refresh" content="1800;/">
	<title>Nav - 晨星导航</title>
	<meta name="description" content="这是个为在校Web开发者打造的导航页">
	<link rel="shortcut icon" href="{% static 'nav/img/favicon.ico' %}" />
	<link rel="apple-touch-icon" href="{% static 'nav/img/favicon.png' %}">
	<!--https://fontawesome.com/v6/icons?m=free-->
	<link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
	{% compress css %}
	<link rel="stylesheet" href="{% static 'nav/css/style.css' %}">
	{% endcompress %}
	<link rel="stylesheet" href="{% static 'node_modules/pace-js/pace-theme-default.min.css' %}">
	{% tracking_code %}
</head>

<body>
	<div id="container">
		<!-- headBar -->
		<div class="sticky top-0 w-full flex-col items-center flex md:hidden text-orange-400">
			<div id="headBarTitle" class="title text-center text-3xl">
				晨星导航
			</div>
			<nav id="headBarNav" class="nav flex justify-between w-10/12">
				{% for category in categories %}
				<a href="#{{ category.slug }}" class="text-lg">
					<i class="{{ category.icon }}"></i>
				</a>
				{% endfor %}
				<a href="{% url 'blog:contact' %}" target="_blank" class="text-lg">
					<i class="fa-solid fa-at"></i>
				</a>
			</nav>
		</div>

		<!-- leftBar -->
		<div class="w-1/6 hidden md:block md:fixed h-screen bg-gray-400 py-4 text-center">
			<div class="text-2xl lg:text-3xl xl:text-4xl text-green-500">
				晨星导航
			</div>
			<nav>
				<ul>
					{% for category in categories %}
					<li class="my-2">
						<a href="#{{ category.slug }}">
							<span
								class="{{ category.icon }} text-base lg:text-lg xl:text-xl font-bold hover:text-cyan-400">
								{{ category.name }}
							</span>
						</a>
					</li>
					{% endfor %}
				</ul>
			</nav>
			<div class="absolute bottom-4 w-full">
				{% if user.is_authenticated %}
				<div class="text-lg font-bold">
					<span>UserName: </span>
					<span>{{user.username}}</span>
				</div>
				{% endif %}

				<a href="{% url 'blog:contact' %}" target="_blank">
					<span class="fa-solid fa-at">留言</span>
				</a>
				<a href="{% url 'blog:index' %}" target="_blank">
					<span class="fa-solid fa-house">主页</span>
				</a>
			</div>
		</div>

		<!-- mainPart -->
		<div class="flex">
			<!-- 实现margin-1/6 -->
			<div class="w-1/6 hidden md:block"></div>
			<div id="main" class="w-full md:w-5/6">
				{% for category in categories %}
				<section class="py-4">
					<a href="#" id="{{ category.slug }}"></a>
					<div class="category mb-3 pl-6">
						<span class="{{category.icon}} text-2xl"> {{category.name}}</span>
					</div>
					<div
						class="grid justify-around grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 pr-8 pl-4">
						{% for item in category.items %}

						{% if item.level == "admin" and not user.is_superuser %}
						{% else %}

						{% if item.display == "hide" %}

						{% elif item.display == "modal" %}
						<div class="neumorphism rounded-3xl">
							<label for="modal-{{ item.slug }}"
								class="modal-button cursor-pointer w-full block py-4 pl-6 font-bold text-lg">
								<div class="flex items-center">
									{% if item.image %}
									<img src="{{ item.image }}" alt="{{item.name}}的图片" class="rounded-full w-10 h-10">
									{% endif %}
									<div class="font-bold text-lg pl-2">{{item.name}}</div>
								</div>
							</label>
							<input type="checkbox" id="modal-{{ item.slug }}" class="modal-toggle" />
							<label for="modal-{{ item.slug }}" class="modal cursor-pointer">
								<div class="modal-box">
									<h1 class="text-3xl font-bold">{{ item.name }}</h1>
									<ul class="pl-8 py-4">
										{% for entry in item.entries %}
										<li
											class="{% if entry.class == 'special' %} text-red-400 {% endif %} hover:text-lime-400 custom-list-style">
											<a href="{{ entry.link }}" target="_blank" class="cursor-pointer text-lg">
												{{ entry.name}}
											</a>
										</li>
										{% endfor %}
									</ul>
									<div class="modal-action">
										<label for="modal-{{ item.slug }}" class="btn">Yay!</label>
									</div>
								</div>
							</label>
						</div>
						{% else %}
						<a class="neumorphism rounded-3xl hover:translate-x-2 transition duration-300 delay-75 ease-linear"
							target="_blank" href="{{item.url}}">
							<div class="flex items-center pl-6 py-4">
								{% if item.image %}
								<img src="{{ item.image }}" alt="{{item.name}}的图片" class="rounded-full w-10 h-10">
								{% endif %}
								<div class="font-bold text-lg pl-2">{{item.name}}</div>
							</div>
							{% if item.desc %}
							<div class="desc relative bottom-2 indent-4">{{item.desc}}</div>
							{% endif %}
						</a>
						{% endif %}

						{% endif %}

						{% endfor %}
					</div>
				</section>
				{% endfor %}

				<footer class="pb-2">
					<div class="text-center">
						<div id="runtime_span"></div>
						<div id="copyright">
							<span>© 2022
								<a href="{% url 'me' %}" class="font-bold" style="font-family: Lora">Henry Ji</a>
							</span>
							<span class="brightness-0">/</span>
							<span>License: <a href="https://www.gnu.org/licenses/agpl-3.0.en.html"
									class="font-bold">AGPLv3</a></span>
							<span class="brightness-0">/</span>
							<span>Powered by <a href="https://www.djangoproject.com/"
									class="font-bold">Django</a></span>
						</div>
					</div>
					{% compress js %}
					<script src="{% static 'base/js/runtime.js' %}"></script>
					{% endcompress %}
				</footer>
			</div>
		</div>
	</div>
</body>

{% compress js %}
<script src="{% static 'nav/js/app.js' %}"></script>
{% endcompress %}

<script src="{% static 'node_modules/pace-js/pace.min.js' %}"></script>
<script data-href="https://github.com/HenryJi529/OpenMorningstar"
	src="{% static 'node_modules/github-corners/dist/embed.min.js' %}"></script>

</html>