Morningstar/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.views.generic.base import TemplateView
from django.contrib.sitemaps.views import sitemap
from django.views.decorators.cache import cache_page
from rest_framework import routers
from rest_framework.documentation import include_docs_urls

from Morningstar.settings.common import CACHE_TIMEOUT
from Morningstar.settings.common import MEDIA_ROOT

from .views import dev, info, shortcut, tool
from .sitemaps import Sitemaps

router = routers.DefaultRouter()


infoUrls = [
    path("favicon.ico", cache_page(CACHE_TIMEOUT)(info.get_favicon), name="favicon"),
    path("qrcode/", cache_page(CACHE_TIMEOUT)(info.get_qrcode), name="qrcode"),
    path("me/", cache_page(CACHE_TIMEOUT)(info.me), name="me"),
    path("credits/", cache_page(CACHE_TIMEOUT)(info.credits), name="credits"),
    path(
        "sitemap.xml",
        cache_page(CACHE_TIMEOUT)(sitemap),
        {"sitemaps": Sitemaps},
        name="sitemap",
    ),
    path("dev/", dev.index, name="dev_index"),
    path(
        "shortcut/<slug:name>/",
        cache_page(CACHE_TIMEOUT)(shortcut.shortcut),
        name="shortcut",
    ),
    path(
        "robots.txt",
        cache_page(CACHE_TIMEOUT)(
            TemplateView.as_view(
                template_name="base/robots.txt", content_type="text/plain"
            )
        ),
    ),
]

authUrls = [
    path("get-image-captcha/", tool.get_image_captcha, name="get_image_captcha"),
    path("activate-by-email/", tool.activate_by_email, name="activate_by_email"),
    path(
        "send-phone-code/<slug:template>/", tool.send_phone_code, name="send_phone_code"
    ),
    path(
        "send-email-code/<slug:template>/", tool.send_email_code, name="send_email_code"
    ),
    path(
        "get-login-token/<slug:identity>/", tool.get_login_token, name="get_login_token"
    ),
    path("login-by-token/<str:token>/", tool.login_by_token, name="login_by_token"),
]


urlpatterns = (
    infoUrls
    + authUrls
    + [
        path("", include("blog.urls")),
        path("api/joke/", include("joke.urls")),
        path("lover/", include("lover.urls")),
        path("nav/", include("nav.urls")),
        path("proxy/", include("proxy.urls")),
        path("api/recognizer/", include("recognizer.urls")),
        path("rss/", include("rss.urls")),
        path("api/share/", include("share.urls")),
        # 调试
        path("debug/", include("debug_toolbar.urls")),
        # 媒体
        re_path(r"media/(?P<path>.*)$", serve, {"document_root": MEDIA_ROOT}),
        # 管理
        path("admin/", admin.site.urls, name="admin"),
        # restful api
        # path("api/", include(router.urls)), # TODO: 未来需要更规范的使用
        path("docs/", include_docs_urls(title="API文档", description="hiahiahia")),
    ]
)

apps/blog/urls.py
from django.urls import path
from django.urls import include
from Morningstar.settings.common import CACHE_TIMEOUT
from django.views.decorators.cache import cache_page

from . import feeds
from . import views

app_name = "blog"
urlpatterns = [
    path("contact/", views.contact, name="contact"),
    path("search/", views.BlogSearchView(), name="search"),
    path("feed/", cache_page(CACHE_TIMEOUT)(feeds.AllPostsRssFeed()), name="feed"),
    path("", views.IndexView.as_view(), name="index"),
    path("posts/<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path(
        "archives/<int:year>/<int:month>/", views.ArchiveView.as_view(), name="archive"
    ),
    path("categories/<int:pk>/", views.CategoryView.as_view(), name="category"),
    path("tags/<int:pk>/", views.TagView.as_view(), name="tag"),
    path("comment/<int:post_pk>", views.comment, name="comment"),
    path("thumbs/", views.thumbs, name="thumbs"),
    # 账号相关
    path("logout/", views.logout, name="logout"),
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("updateInfo/", views.updateInfo, name="updateInfo"),
    path("updatePassword/", views.updatePassword, name="updatePassword"),
    path("updateEmail/", views.updateEmail, name="updateEmail"),
    path("updatePhone/", views.updatePhone, name="updatePhone"),
]

apps/blog/models.py
from django.db import models
from Morningstar.models import User
from django.utils import timezone
from django.urls import reverse
from django.utils.html import strip_tags
from django.utils.functional import cached_property
import markdown
import readtime

from Morningstar.models import User


MARKDOWN_EXTENSIONS = [
    "markdown.extensions.toc",  # 目录
    "pymdownx.betterem",  # 处理强调
    "pymdownx.caret",  # 提供<ins>和<sup>标签
    "pymdownx.highlight",  # 高亮代码(标记语言)
    "pymdownx.superfences",  # 处理代码块
    "pymdownx.arithmatex",  # 数学公式
    "markdown.extensions.tables",  # 表格
]

MARKDOWN_EXTENSION_CONFIGS = {
    "pymdownx.highlight": {
        "guess_lang": True,
        "css_class": "highlight",
        "use_pygments": False,
    },
    "pymdownx.arithmatex": {
        "generic": True,
    },
}


class Category(models.Model):
    """
    分类
    """

    name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name = "分类"
        verbose_name_plural = verbose_name
        ordering = ["name"]

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    标签
    """

    name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name
        ordering = ["name"]

    def __str__(self):
        return self.name


class Post(models.Model):
    """
    文章
    """

    title = models.CharField("标题", max_length=50)
    body = models.TextField("正文")
    created = models.DateTimeField(
        "创建时间", auto_now_add=True
    )  # 比datetime增加时区处理
    updated = models.DateTimeField("修改时间", auto_now=True)
    excerpt = models.CharField("摘要", max_length=120, blank=True)
    category = models.ForeignKey(
        Category, verbose_name="分类", on_delete=models.CASCADE, blank=True
    )
    tags = models.ManyToManyField(Tag, verbose_name="标签", blank=True)
    readtime = models.IntegerField("阅读时间", default=0, null=True, blank=True)
    views = models.PositiveIntegerField(default=0, editable=False)  # 不可修改!
    requireLogin = models.BooleanField(default=False)

    @property
    def toc(self):
        return self.rich_content.get("toc", "")

    @property
    def html(self):
        return self.rich_content.get("content", "")

    @cached_property
    def rich_content(self):
        md = markdown.Markdown(
            extensions=MARKDOWN_EXTENSIONS,
            extension_configs=MARKDOWN_EXTENSION_CONFIGS,
        )
        content = md.convert(self.body)
        toc = md.toc
        return {"content": content, "toc": toc}

    def increase_views(self):
        self.views += 1
        self.save(update_fields=["views"])

    def save(self, *args, **kwargs):
        md = markdown.Markdown(
            extensions=MARKDOWN_EXTENSIONS,
            extension_configs=MARKDOWN_EXTENSION_CONFIGS,
        )
        self.excerpt = strip_tags(md.convert(self.body))[:120]  # 获取摘要
        self.readtime = (
            self.readtime
            if self.readtime
            else int(readtime.of_markdown(self.body, wpm=200).seconds / 60)
        )  # 设置默认值
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name
        ordering = ["-updated", "-created", "title"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"pk": self.pk})


class Comment(models.Model):
    user = models.ForeignKey(
        User, verbose_name="用户", on_delete=models.SET_NULL, null=True
    )
    body = models.TextField("内容")
    created = models.DateTimeField("创建时间", auto_now_add=True)
    updated = models.DateTimeField("修改时间", auto_now=True)
    post = models.ForeignKey(Post, verbose_name="文章", on_delete=models.CASCADE)
    thumbs_up = models.ManyToManyField(
        User, related_name="thumbsUp_user", verbose_name="点赞"
    )
    thumbs_down = models.ManyToManyField(
        User, related_name="thumbsDown_user", verbose_name="点踩"
    )

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name
        ordering = ["-updated", "-created"]

    @property
    def html(self):
        md = markdown.Markdown(
            extensions=MARKDOWN_EXTENSIONS,
            extension_configs=MARKDOWN_EXTENSION_CONFIGS,
        )
        return md.convert(self.body)

    def __str__(self):
        return "{}: {}".format(self.user.username, self.body[:20])

apps/blog/forms.py
import jieba

from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["body"].widget.attrs.update(
            {
                "class": "auto-expend form-control rounded-xl w-full p-2 border-slate-200 bg-transparent",
                "placeholder": "留条评论呗～",
                "rows": "4",
            }
        )

    class Meta:
        model = Comment
        fields = ["body"]


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100, required=False)
    email = forms.EmailField(label="Your e-mail address", required=False)
    message = forms.CharField(required=True)

    def clean_message(self):
        message = self.cleaned_data["message"]
        if len(list(jieba.cut(message))) < 4:
            raise forms.ValidationError("内容不够长哎!")
        return message

Morningstar/views/base.py
import json
import os
import random
import logging

from django.http import HttpResponse, JsonResponse, Http404, HttpRequest
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.hashers import make_password
from django.contrib.sessions.models import Session
from django.contrib import auth
from django.contrib import messages
from django_redis import get_redis_connection

from ..forms import LoginForm, RegisterForm
from ..models import User
from ..lib.auth import authenticate
from ..lib.mail import send_mail_from_host

logger = logging.getLogger("django")


def fix_fetched_post(request: HttpRequest):
    try:
        # fetch请求
        post_data = json.loads(request.body.decode("utf-8"))
        request.POST._mutable = True
        for key, value in post_data.items():
            request.POST[key] = value
        request.POST._mutable = False
    except:
        # 基本请求
        pass
    return request


def handle_register(request: HttpRequest, is_api=True):
    def create_activate_message(username, host):
        code = random.randint(10000, 99999)
        conn = get_redis_connection("default")
        try:
            conn.delete(f"{username}-activate")
        except:
            pass
        conn.set(f"{username}-activate", code, ex=60 * 10)
        protocol = "https://" if request.is_secure() else "http://"
        link = (
            protocol
            + host
            + reverse("activate_by_email")
            + f"?username={username}&code={code}"
        )
        message = f"通过该链接激活:\n{link}\n十分钟内有效..."

        return message

    form = RegisterForm(request.POST)
    if form.is_valid():
        email = form.cleaned_data.get("email")
        phone = form.cleaned_data.get("phone")
        code = form.cleaned_data.get("code")
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        confirm_password = form.cleaned_data.get("confirm_password")

        user = User.objects.create(
            username=username,
            password=make_password(password),
            email=email,
            is_active=False,
        )
        subject = "激活邮件"
        message = create_activate_message(
            username=username, host=request.META["HTTP_HOST"]
        )
        send_mail_from_host(subject, message, [email])
        if is_api:
            response_data = {"status": "success", "message": "成功通过邮箱注册"}
            return JsonResponse(response_data)
        else:
            messages.add_message(request, messages.INFO, "注册已完成...请通过邮箱激活")
            next = request.POST.get("next", "/")
            return redirect(next if next else "/")
    else:
        if is_api:
            return JsonResponse({"status": "error", "message": form.errors})
        else:
            messages.add_message(request, messages.WARNING, form.errors)
            next = request.POST.get("next", "/")
            return redirect(next if next else "/")


def handle_login(request, is_api=False):
    form = LoginForm(request, request.POST)
    if form.is_valid():
        identity = form.cleaned_data.get("identity")
        password = form.cleaned_data.get("password")

        # NOTE: 使用增强后的认证函数
        user = authenticate(identity=identity, password=password)
        if user is not None:
            auth.login(request, user)
            next = request.POST.get("next", "/")
            if is_api:
                return JsonResponse({"status": "success", "message": "登录成功"})
            else:
                messages.add_message(request, messages.INFO, "登录成功...")
                return redirect(next if next else "/")
        else:
            if is_api:
                return JsonResponse(
                    {"status": "error", "message": "账号不存在或密码错误..."}
                )
            else:
                messages.add_message(request, messages.ERROR, "账号不存在或密码错误...")
                return redirect("/")
    else:
        if is_api:
            return JsonResponse(
                {"status": "error", "message": form.errors["image_captcha"][0]}
            )
        else:
            messages.add_message(
                request, messages.ERROR, form.errors["image_captcha"][0]
            )
            return redirect("/")

apps/blog/templates/blog/comment_preview.html
{% extends 'blog/base.html' %}
{% load comments_extras %}

{% block main %}
{% show_comment_form post request.user form %}
{% endblock main %}

apps/blog/templates/blog/contact.html
{% extends 'blog/base.html' %}


{% block main %}
<div class="p-4">
	<div class="text-3xl pb-3">联系站长</div>
	<article>
		<div>
			<form id="contactForm" action="{% url 'blog:contact' %}" method="POST">
				{% csrf_token %}
				<div>
					<input type="email" placeholder="邮箱" class="input input-ghost w-full" name="email" />
					<input type="text" placeholder="主题" class="input input-ghost w-full" name="subject" required />
					<textarea class="textarea w-full" rows="7" name="message" placeholder="你的网站太棒了呢(字数太少站长收不到哟～)"
						required></textarea>
					<button class="btn"><span>发送</span></button>
				</div>
			</form>
		</div>
	</article>
</div>
{% endblock main %}

apps/blog/templates/blog/contact_thanks.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'blog/css/base.css' %}">
	<title>Contact - 感谢联系</title>
</head>

<body>
	<div class="container min-h-screen p-8 mt-8">
		<div class="text-5xl text-center mb-8">
			感谢联系
		</div>
		<div class="flex justify-center">
			<div class="radial-progress text-3xl" style="--value:0;--size:12rem;" id="radialProgress">0%</div>
		</div>
	</div>
</body>

{% compress js %}
<script src="{% static 'blog/js/toggleTheme.js' %}"></script>
{% endcompress %}

<script>
	const radialProgress = document.querySelector('#radialProgress');
	const progressInterval = setInterval(() => {
		const currentValue = Number(radialProgress.style.getPropertyValue('--value'));
		radialProgress.style.setProperty('--value', currentValue + 10);
		radialProgress.innerText = `${currentValue + 10}%`;
		if (currentValue === 90) {
			clearInterval(progressInterval);
			window.location.href = "{% url 'blog:contact' %}";
		}
	}, 500);
</script>

</html>

apps/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load compress %}
{% load comments_extras %}
{% load blog_extras %}

{% block custom_css %}

{% compress css %}
<link rel="stylesheet" href="{% static 'node_modules/highlight.js/styles/github.css' %}">
{% endcompress %}

{% endblock custom_css %}

{% block main %}
<article class="post">
    <div class="post-header flex flex-col items-center mb-8">
        <a class="text-center text-4xl block pb-2" href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
        <div class="flex justify-center text-sm text-center space-x-2">
            <span>
                <i class="fa-solid fa-folder"></i>
                <a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a>
            </span>
            {% if post.tags.all %}
            <span>
                <i class="fa-solid fa-tag"></i>
                {% for tag in post.tags.all %}
                <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                {% if not forloop.last %}
                <span>|</span>
                {% endif %}
                {% endfor %}
            </span>
            {% endif %}
            <span>
                <i class="fa-solid fa-comment"></i>
                <a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }}</a></span>
            <span>
                <i class="fa-solid fa-eye"></i>
                <a href="{% url 'blog:detail' post.pk %}">{{ post.views }}</a>
            </span>
            <span>
                <i class="fa-solid fa-pen"></i>
                <time>{{ post.created|date:"Y-m-d" }}</time>
            </span>
            <span>
                <i class="fa-solid fa-rotate"></i>
                <time>{{ post.updated|date:"Y-m-d" }}</time>
            </span>
            <span>
                <i class="fa-solid fa-clock-rotate-left"></i>
                <time>{{ post.readtime }}min</time>
            </span>
        </div>
    </div>

    <div class="post-body">
        {% if post.requireLogin %}

        {% if user.is_authenticated %}
        {{ post.html|safe }}
        {% else %}
        <p class="text-pink-500 text-3xl">欲知详情，还请登录～</p>
        {% endif %}

        {% else %}

        {{ post.html|safe }}
        {% endif %}
    </div>

</article>

<div class="divider"></div>

<section id="comment-area">
    <div class="pb-4">
        {% show_comments post user %}
    </div>
    <div class="pb-4">
        {% show_comment_form post %}
    </div>
</section>
{% endblock main %}

{% block toc %}

{% toc_not_null post.toc as tocNotNull %}
{% if tocNotNull %}
<div class="widget p-2 relative">
    <input class="widget-toggle hidden absolute w-full" type="checkbox" />
    <h3 class="widget-title text-2xl">目录</h3>
    <div class="widget-list toc">
        {{ post.toc|safe }}
    </div>
</div>
<div class="divider"></div>
{% endif %}

{% endblock toc %}

{% block custom_js %}

{% compress js %}
<script src="{% static 'blog/dist/highlight.bundle.js' %}"></script>
{% endcompress %}

<script src="{% static 'node_modules/mathjax/es5/tex-mml-chtml.js' %}"></script>
{% endblock custom_js %}

apps/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block main %}
{% for post in post_list %}
<article class="p-4 m-3">
    <div class="flex flex-col items-center">
        <a class="text-center text-2xl block" href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
        <div class="flex justify-center text-sm text-center space-x-2 overflow-x-scroll">
            <span>
                <i class="fa-solid fa-folder"></i>
                <a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a>
            </span>
            {% if post.tags.all %}
            <span>
                <i class="fa-solid fa-tag"></i>
                {% for tag in post.tags.all %}
                <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                {% if not forloop.last %}
                <span>|</span>
                {% endif %}
                {% endfor %}
            </span>
            {% endif %}
            <span>
                <i class="fa-solid fa-eye"></i>
                <a href="{% url 'blog:detail' post.pk %}">{{ post.views }}</a>
            </span>
            <span>
                <i class="fa-solid fa-clock-rotate-left"></i>
                <time>{{ post.readtime }}min</time>
            </span>
        </div>
    </div>
    <div>
        <p class="indent-8">{{ post.excerpt }}...</p>
        <div class="flex justify-center">
            <a href="{{ post.get_absolute_url }}" class="italic">继续阅读 <span>→</span></a>
        </div>
    </div>
</article>
{% empty %}
<div>暂时还没有发布的文章！</div>
{% endfor %}

{% if is_paginated %}
<div class="flex justify-between text-left">
    <div class="flex-1 text-left text-lg">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}"><i class="fa-solid fa-angles-left"></i> 上一页</a>
        {% else %}
        <div class="invisible"></div>
        {% endif %}
    </div>

    <a href="#" class="current font-bold flex-1 text-center text-lg">
        {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
    </a>

    <div class="flex-1 text-right text-lg">
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">下一页 <i class="fa-solid fa-angles-right"></i></a>
        {% else %}
        <div class="invisible"></div>
        {% endif %}
    </div>
</div>
{% endif %}

{% endblock main %}

apps/blog/templates/blog/search.html
{% extends 'blog/base.html' %}
{% load highlight %}


{% block custom_css %}
<style>
	/* 搜索关键词高亮 */
	/* span.highlighted {
	color: red;
	} */
	span.highlight_me_please {
		color: rgb(226, 54, 83);
	}
</style>
{% endblock %}


{% block main %}
{% if query %}



{% for result in page.object_list %}

{% with post=result.object %}
<article class="p-4 m-3">
	<div class="flex flex-col items-center">
		<a class="text-center text-2xl block" href="{{ post.get_absolute_url }}">
			{% highlight post.title with query html_tag "span" css_class "highlight_me_please"%}
		</a>
		<div class="flex justify-center text-sm text-center space-x-2">
			<span>
				<i class="fa-solid fa-folder"></i>
				<a href="{% url 'blog:category' post.category.pk %}">{{post.category.name}}</a>
			</span>
			<span>
				<i class="fa-solid fa-eye"></i>
				<a href="{% url 'blog:detail' post.pk %}">{{post.views}}</a>
			</span>
			<span>
				<i class="fa-solid fa-clock-rotate-left"></i>
				<time>{{ post.readtime }}min</time>
			</span>
		</div>
	</div>
	<div>
		<p>{% highlight post.excerpt with query html_tag "span" css_class "highlight_me_please" %}</p>
		<div class="flex justify-center">
			<a href="{{ post.get_absolute_url }}" class="italic">继续阅读 <span>→</span></a>
		</div>
	</div>
</article>
{% endwith %}

{% empty %}

<div>没有搜索到你想要的结果！</div>

{% endfor %}


{% with page_obj=page %}
<div class="flex justify-between text-left">
	<div class="flex-1 text-left text-lg">
		{% if page_obj.has_previous %}
		<a href="?q={{ query }}&amp;page={{ page_obj.previous_page_number }}">
			<i class="fa-solid fa-angles-left"></i>上一页
		</a>
		{% else %}
		<div class="invisible"></div>
		{% endif %}
	</div>

	<a href="#" class="current font-bold flex-1 text-center text-lg">
		{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
	</a>

	<div class="flex-1 text-right text-lg">
		{% if page_obj.has_next %}
		<a href="?q={{ query }}&amp;page={{ page_obj.next_page_number }}">
			下一页 <i class="fa-solid fa-angles-right"></i>
		</a>
		{% else %}
		<div class="invisible"></div>
		{% endif %}
	</div>
</div>
{% endwith %}


{% else %}

请输入搜索关键词，例如 django

{% endif %}
{% endblock main %}