Morningstar/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.views.generic.base import TemplateView
from django.contrib.sitemaps.views import sitemap
from django.views.decorators.cache import cache_page
from rest_framework import routers
from rest_framework.documentation import include_docs_urls

from Morningstar.settings.common import CACHE_TIMEOUT
from Morningstar.settings.common import MEDIA_ROOT

from .views import dev, info, shortcut, tool
from .sitemaps import Sitemaps

router = routers.DefaultRouter()


infoUrls = [
    path("favicon.ico", cache_page(CACHE_TIMEOUT)(info.get_favicon), name="favicon"),
    path("qrcode/", cache_page(CACHE_TIMEOUT)(info.get_qrcode), name="qrcode"),
    path("me/", cache_page(CACHE_TIMEOUT)(info.me), name="me"),
    path("credits/", cache_page(CACHE_TIMEOUT)(info.credits), name="credits"),
    path(
        "sitemap.xml",
        cache_page(CACHE_TIMEOUT)(sitemap),
        {"sitemaps": Sitemaps},
        name="sitemap",
    ),
    path("dev/", dev.index, name="dev_index"),
    path(
        "shortcut/<slug:name>/",
        cache_page(CACHE_TIMEOUT)(shortcut.shortcut),
        name="shortcut",
    ),
    path(
        "robots.txt",
        cache_page(CACHE_TIMEOUT)(
            TemplateView.as_view(
                template_name="base/robots.txt", content_type="text/plain"
            )
        ),
    ),
]

authUrls = [
    path("get-image-captcha/", tool.get_image_captcha, name="get_image_captcha"),
    path("activate-by-email/", tool.activate_by_email, name="activate_by_email"),
    path(
        "send-phone-code/<slug:template>/", tool.send_phone_code, name="send_phone_code"
    ),
    path(
        "send-email-code/<slug:template>/", tool.send_email_code, name="send_email_code"
    ),
    path(
        "get-login-token/<slug:identity>/", tool.get_login_token, name="get_login_token"
    ),
    path("login-by-token/<str:token>/", tool.login_by_token, name="login_by_token"),
]


urlpatterns = (
    infoUrls
    + authUrls
    + [
        path("", include("blog.urls")),
        path("api/joke/", include("joke.urls")),
        path("lover/", include("lover.urls")),
        path("nav/", include("nav.urls")),
        path("proxy/", include("proxy.urls")),
        path("api/recognizer/", include("recognizer.urls")),
        path("rss/", include("rss.urls")),
        path("api/share/", include("share.urls")),
        # 调试
        path("debug/", include("debug_toolbar.urls")),
        # 媒体
        re_path(r"media/(?P<path>.*)$", serve, {"document_root": MEDIA_ROOT}),
        # 管理
        path("admin/", admin.site.urls, name="admin"),
        # restful api
        # path("api/", include(router.urls)), # TODO: 未来需要更规范的使用
        path("docs/", include_docs_urls(title="API文档", description="hiahiahia")),
    ]
)

apps/blog/urls.py
from django.urls import path
from django.urls import include
from Morningstar.settings.common import CACHE_TIMEOUT
from django.views.decorators.cache import cache_page

from . import feeds
from . import views

app_name = "blog"
urlpatterns = [
    path("contact/", views.contact, name="contact"),
    path("search/", views.BlogSearchView(), name="search"),
    path("feed/", cache_page(CACHE_TIMEOUT)(feeds.AllPostsRssFeed()), name="feed"),
    path("", views.IndexView.as_view(), name="index"),
    path("posts/<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path(
        "archives/<int:year>/<int:month>/", views.ArchiveView.as_view(), name="archive"
    ),
    path("categories/<int:pk>/", views.CategoryView.as_view(), name="category"),
    path("tags/<int:pk>/", views.TagView.as_view(), name="tag"),
    path("comment/<int:post_pk>", views.comment, name="comment"),
    path("thumbs/", views.thumbs, name="thumbs"),
    # 账号相关
    path("logout/", views.logout, name="logout"),
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("updateInfo/", views.updateInfo, name="updateInfo"),
    path("updatePassword/", views.updatePassword, name="updatePassword"),
    path("updateEmail/", views.updateEmail, name="updateEmail"),
    path("updatePhone/", views.updatePhone, name="updatePhone"),
]

apps/blog/forms.py
import jieba

from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["body"].widget.attrs.update(
            {
                "class": "auto-expend form-control rounded-xl w-full p-2 border-slate-200 bg-transparent",
                "placeholder": "留条评论呗～",
                "rows": "4",
            }
        )

    class Meta:
        model = Comment
        fields = ["body"]


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100, required=False)
    email = forms.EmailField(label="Your e-mail address", required=False)
    message = forms.CharField(required=True)

    def clean_message(self):
        message = self.cleaned_data["message"]
        if len(list(jieba.cut(message))) < 4:
            raise forms.ValidationError("内容不够长哎!")
        return message

apps/blog/views.py
import re
import json

from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.http import (
    HttpResponseRedirect,
    HttpResponse,
    Http404,
    JsonResponse,
    HttpRequest,
)
from django.urls import reverse
from django.views import generic
from django.views.decorators.http import require_POST
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.views.generic import ListView, DetailView
from django.db.models import Q

from django.core.mail import send_mail
from haystack import views as haystack_views

from Morningstar.views.base import handle_login, handle_register
from Morningstar.views.base import fix_fetched_post
from Morningstar.settings.common import EMAIL_HOST_USER, DEFAULT_GUEST_EMAIL
from Morningstar.forms import (
    LoginForm,
    RegisterForm,
    InfoForm,
    UpdateEmailForm,
    UpdatePhoneForm,
    UpdatePasswordForm,
)
from Morningstar.lib.print import colored_format
from Morningstar.lib.mail import send_mail_from_host
from Morningstar.models import User

from .models import Category, Post, Tag, Comment
from .forms import CommentForm, ContactForm


class BlogSearchView(haystack_views.SearchView):
    template = "blog/search.html"


class CustomListView(ListView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["login_form"] = LoginForm(self.request)
        context["register_form"] = RegisterForm()
        if self.request.user.is_authenticated:
            context["info_form"] = InfoForm(
                initial={
                    "nickname": self.request.user.nickname,
                    "bio": self.request.user.bio,
                    "avatar": self.request.user.avatar,
                }
            )
        else:
            context["info_form"] = InfoForm()
        return context


class CustomDetailView(DetailView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["login_form"] = LoginForm(self.request)
        context["register_form"] = RegisterForm()
        if self.request.user.is_authenticated:
            context["info_form"] = InfoForm(
                initial={
                    "nickname": self.request.user.nickname,
                    "bio": self.request.user.bio,
                }
            )
        else:
            context["info_form"] = InfoForm()
        return context


class IndexView(CustomListView):
    model = Post
    template_name = "blog/index.html"
    context_object_name = "post_list"
    paginate_by = 10


class ArchiveView(IndexView):
    def get_queryset(self):
        year = self.kwargs.get("year")
        month = self.kwargs.get("month")
        return (
            super(ArchiveView, self)
            .get_queryset()
            .filter(created__year=year, created__month=month)
        )


class CategoryView(IndexView):
    def get_queryset(self):
        # 从URL捕获的路径参数值保存在实例的kwargs字典里，非路径参数值保存在实例的args列表里。
        cate = get_object_or_404(Category, pk=self.kwargs.get("pk"))
        return super(CategoryView, self).get_queryset().filter(category=cate)


class TagView(IndexView):
    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get("pk"))
        return super(TagView, self).get_queryset().filter(tags=tag)


class PostDetailView(CustomDetailView):
    model = Post
    template_name = "blog/detail.html"
    context_object_name = "post"

    def get(self, request, *args, **kwargs):
        # get 方法返回的是一个 HttpResponse 实例
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()
        return response


def contact(request: HttpRequest):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            subject = cd["subject"]
            message = request.POST["message"]
            email = cd.get("email") if len(cd.get("email")) > 0 else DEFAULT_GUEST_EMAIL
            from_email = email.replace("@", "*") + "<" + EMAIL_HOST_USER + ">"
            send_mail(
                subject,
                message,
                from_email,
                ["jeep.jipu@gmail.com"],
            )
            return render(request, "blog/contact_thanks.html")
        else:
            messages.add_message(request, messages.ERROR, form.errors["message"][0])
            return render(request, "blog/contact.html")
    else:
        return render(request, "blog/contact.html")


@require_POST
def comment(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        # commit=False 的作用是仅仅利用表单的数据生成 Comment 模型类的实例，但还不保存评论数据到数据库。
        comment = form.save(commit=False)
        comment.user = request.user
        comment.post = post
        comment.save()
        # 重定向到 post 的详情页，实际上当 redirect 函数接收一个模型的实例时，它会调用这个模型实例的 get_absolute_url 方法，
        # 然后重定向到 get_absolute_url 方法返回的 URL。
        messages.add_message(
            request, messages.SUCCESS, "评论发表成功！", extra_tags="success"
        )

        # 检测是否有回复他人
        pattern = re.compile(r"\[@[\w-]*?\]\(#comment-\d*?\)", re.M)
        matches = pattern.findall(request.POST["body"])
        if matches:
            for match in matches:
                # 获取回复的用户
                username = re.search(r"\[@([\w-]*?)\]", match).group(1)
                comment_id = re.search(r"\(#comment-(\d*?)\)", match).group(1)
                if Comment.objects.get(id=comment_id).user.username == username:
                    # 发送邮件通知
                    subject = "您在晨星小站的评论有了新的回复"
                    post = Comment.objects.get(id=comment_id).post
                    message = f"您在《{post.title}》的评论中有了新的回复, 点击链接查看: \nhttps://morningstar369.com{post.get_absolute_url()}#comment-{comment.id}\n"
                    to_email = User.objects.get(username=username).email
                    send_mail_from_host(subject, message, [to_email])
        else:
            pass
        return redirect(post)

    # 检查到数据不合法，我们渲染一个预览页面，用于展示表单的错误。
    # 注意这里被评论的文章 post 也传给了模板，因为我们需要根据 post 来生成表单的提交地址。
    context = {
        "post": post,
        "form": form,
    }
    messages.add_message(
        request,
        messages.ERROR,
        "评论发表失败！请修改表单中的错误后重新提交。",
        extra_tags="danger",
    )
    return render(request, "blog/comment_preview.html", context=context)


@require_POST
def thumbs(request: HttpRequest):
    try:
        request = fix_fetched_post(request)
        action = request.POST["action"]
        direction = request.POST["direction"]
        comment = Comment.objects.get(id=request.POST["comment_id"])
        if action == "do" and direction == "up":
            comment.thumbs_up.add(request.user)
            print(comment.thumbs_up.all())
        elif action == "do" and direction == "down":
            comment.thumbs_down.add(request.user)
        elif action == "undo" and direction == "up":
            comment.thumbs_up.remove(request.user)
        elif action == "undo" and direction == "down":
            comment.thumbs_down.remove(request.user)
        else:
            pass
        comment.save()
        return JsonResponse(
            {
                "status": "success",
                "thumbsUp_count": comment.thumbs_up.all().count(),
                "thumbsDown_count": comment.thumbs_down.all().count(),
            }
        )
    except:
        return JsonResponse({"status": "error"})


@login_required(login_url="/")
# @login_required(login_url=reverse("blog:index")) # NOTE: 别！！！
def logout(request: HttpRequest):
    auth.logout(request)
    return redirect(reverse("blog:index"))


def register(request: HttpRequest):
    return handle_register(request, is_api=False)


def login(request: HttpRequest):
    return handle_login(request, is_api=False)


@require_POST
def updateInfo(request: HttpRequest):
    info_form = InfoForm(request.POST, request.FILES)
    if info_form.is_valid():
        request.user.nickname = info_form.cleaned_data["nickname"]
        request.user.bio = info_form.cleaned_data["bio"]
        if info_form.cleaned_data["avatar"]:
            request.user.avatar = info_form.cleaned_data["avatar"]
        request.user.save()
        messages.add_message(request, messages.INFO, "档案更新成功...")
    else:
        print(colored_format(info_form.errors))
        messages.add_message(request, messages.ERROR, "档案更新失败...")
    return redirect(reverse("blog:index"))


@require_POST
def updatePassword(request: HttpRequest):
    update_password_form = UpdatePasswordForm(request.POST)
    if update_password_form.is_valid():
        password = update_password_form.cleaned_data["confirm_password"]
        request.user.set_password(password)
        request.user.save()
        messages.add_message(request, messages.INFO, "密码修改成功...")
    else:
        error_message = [
            value[0]["message"]
            for value in json.loads(update_password_form.errors.as_json()).values()
        ][0]
        messages.add_message(request, messages.ERROR, error_message)
    return redirect(reverse("blog:index"))


@require_POST
def updateEmail(request: HttpRequest):
    update_email_form = UpdateEmailForm(request.POST)
    if update_email_form.is_valid():
        request.user.email = update_email_form.cleaned_data["email"]
        request.user.save()
        messages.add_message(request, messages.INFO, "邮箱修改成功...")
    else:
        messages.add_message(
            request, messages.ERROR, update_email_form.errors["email_code"][0]
        )
    return redirect(reverse("blog:index"))


@require_POST
def updatePhone(request: HttpRequest):
    update_phone_form = UpdatePhoneForm(request.POST)
    if update_phone_form.is_valid():

apps/blog/templates/blog/inclusions/_archives.html
<section class="widget p-2 relative">
	<input class="widget-toggle hidden absolute w-full" type="checkbox" />
	<div class="widget-title text-2xl">归档</div>
	<ul class="widget-list">
		{% for date in date_list %}
		<li>
			<i class="fa-solid fa-box-archive"></i>
			<a href="{% url 'blog:archive' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
		</li>
		{% empty %}
		暂无归档！
		{% endfor %}
	</ul>
</section>
<div class="divider"></div>

apps/blog/templates/blog/inclusions/_categories.html
<section class="widget p-2 relative">
	<input class="widget-toggle hidden absolute w-full" type="checkbox" />
	<div class="widget-title text-2xl">分类</div>
	<ul class="widget-list">
		{% for category in category_list %}
		<li>
			<i class="fa-solid fa-folder"></i>
			<a href="{% url 'blog:category' category.pk %}">{{category.name }}
				<span>[{{ category.num_posts }}]</span></a>
		</li>
		{% empty %}
		暂无分类！
		{% endfor %}
	</ul>
</section>
<div class="divider"></div>

apps/blog/templates/blog/inclusions/_comment_form.html
<form action="{% url 'blog:comment' post.pk %}" method="POST" class="w-full">
	{% csrf_token %}
	<div class="flex space-x-4 w-full">
		<div class="btn btn-ghost btn-circle avatar">
			<div class="w-14 rounded-full">
				{% if user.username %}
				<img src="/media/{{ user.avatar }}" alt="{{ user.username }}'s avatar">
				{% else %}
				<i class="fa-solid text-5xl fa-circle-user"></i>
				{% endif %}
			</div>
		</div>

		<div class="flex-1 rounded-xl border-2">
			<div class="flex bg-slate-100 dark:bg-slate-600 space-x-4 rounded-t-xl p-2">
				<div class="p-1 cursor-pointer" id="editorButton">编写</div>
				<div class="p-1 cursor-pointer" id="previewButton">预览</div>
			</div>
			<div class="p-2">
				{{ form.body }}
				{{ form.body.errors }}
				<div class="hidden pb-4" id="commentPreview"></div>
			</div>
			<div class="flex justify-end p-2 pt-0">
				{% if user.username %}
				<button type="submit" class="btn">评论</button>
				{% else %}
				<label for="loginModal" class="btn modal-button text-amber-500">登录</label>
				{% endif %}
			</div>
		</div>
	</div>
</form>
<script src="{% static 'node_modules/marked/marked.min.js' %}"></script>
<script src="{% static 'blog/js/commentPreview.js' %}"></script>

apps/blog/templates/blog/inclusions/_comment_list.html
<div class="space-y-4">
	{% for comment in comment_list %}
	{% if comment_list.count > 13 and forloop.counter == 6 %}
	<div class="divider py-6" id="showAllCommentButton">
		<button class="btn bg-gray-500 dark:bg-zinc-900">隐藏了{{comment_list.count|add:-11}}个评论</button>
	</div>
	{% endif %}
	<div class="comment-item flex space-x-4 w-full {% if comment_list.count > 13 and forloop.counter > 5 and comment_list.count|add:-5 > forloop.counter %}hidden{% endif %}"
		id="comment-{{comment.id}}">
		<div class="btn btn-ghost btn-circle avatar">
			<div class="w-14 rounded-full">
				<img src="/media/{{ comment.user.avatar }}" alt="{{ comment.user.username }}'s avatar">
			</div>
		</div>
		<div class="flex-1 rounded-xl border-2">
			<div class="flex justify-between bg-slate-100 dark:bg-slate-600 rounded-t-xl p-2">
				<div class="flex space-x-2">
					<span class="font-bold">{{ comment.user.username }}</span>
					<div>评论于<span>{{comment.updated|timesince}}</span>前</div>
				</div>
				<div class="flex items-center space-x-2">
					<form action="{% url 'blog:thumbs' %}" method="post" class="flex space-x-2 items-center">
						{% csrf_token %}
						<i class="thumbs-up fa-solid fa-thumbs-up cursor-pointer {% if user in comment.thumbs_up.all %}text-amber-600 text-lg{% else %}{% endif %}"
							data-comment_id="{{comment.id}}"
							data-action="{% if user in comment.thumbs_up.all %}undo{% else %}do{% endif %}"></i>
						<i class="thumbs-down fa-solid fa-thumbs-down cursor-pointer {% if user in comment.thumbs_down.all %}text-amber-600 text-lg{% else %}{% endif %}"
							data-comment_id="{{comment.id}}"
							data-action="{% if user in comment.thumbs_down.all %}undo{% else %}do{% endif %}"></i>
					</form>
					<i class="reply-button fa-solid fa-reply cursor-pointer" data-comment_id="{{comment.id}}"></i>
				</div>
			</div>
			<div class=" comment-body p-2">
				{{ comment.html|safe }}
			</div>

			<div id="commentCountPanel{{comment.id}}"
				class="flex justify-start items-center p-2 pt-1 space-x-2 border-t-2 border-stone-300 dark:border-stone-600 {% if not comment.thumbs_up.all.count and not comment.thumbs_down.all.count %}hidden{% endif %}">
				<div>
					<i class="fa-solid fa-thumbs-up"></i>
					<span data-comment_count="{{comment.id}}-up">{{comment.thumbs_up.all.count}}</span>
				</div>
				<div>
					<i class="fa-solid fa-thumbs-down"></i>
					<span id="id_thumbsDown_count"
						data-comment_count="{{comment.id}}-down">{{comment.thumbs_down.all.count}}</span>
				</div>
			</div>
		</div>
	</div>
	{% empty %}
	{% endfor %}
</div>
<script>
	const thumbs_endpoint = "{% url 'blog:thumbs' %}";
	const csrfToken = "{{ csrf_token }}";
</script>
<script src="{% static 'blog/js/commentShowAll.js' %}"></script>
<script src="{% static 'blog/js/commentThumbs.js' %}"></script>
<script src="{% static 'blog/js/commentReply.js' %}"></script>

apps/blog/templates/blog/inclusions/_hot_posts.html
<section class="widget p-2 relative">
    <input class="widget-toggle hidden absolute w-full" type="checkbox" />
    <div class="widget-title text-2xl">最热</div>
    <ul class="widget-list">
        {% for post in hot_post_list %}
        <li>
            <i class="fa-solid fa-fire"></i>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
        {% empty %}
        暂无文章！
        {% endfor %}
    </ul>
</section>
<div class="divider"></div>

apps/blog/templates/blog/inclusions/_other_links.html
<style>
    .resume-icon::before {
        content: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 640 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M272.2 64.6l-51.1 51.1c-15.3 4.2-29.5 11.9-41.5 22.5L153 161.9C142.8 171 129.5 176 115.8 176H96V304c20.4 .6 39.8 8.9 54.3 23.4l35.6 35.6 7 7 0 0L219.9 397c6.2 6.2 16.4 6.2 22.6 0c1.7-1.7 3-3.7 3.7-5.8c2.8-7.7 9.3-13.5 17.3-15.3s16.4 .6 22.2 6.5L296.5 393c11.6 11.6 30.4 11.6 41.9 0c5.4-5.4 8.3-12.3 8.6-19.4c.4-8.8 5.6-16.6 13.6-20.4s17.3-3 24.4 2.1c9.4 6.7 22.5 5.8 30.9-2.6c9.4-9.4 9.4-24.6 0-33.9L340.1 243l-35.8 33c-27.3 25.2-69.2 25.6-97 .9c-31.7-28.2-32.4-77.4-1.6-106.5l70.1-66.2C303.2 78.4 339.4 64 377.1 64c36.1 0 71 13.3 97.9 37.2L505.1 128H544h40 40c8.8 0 16 7.2 16 16V352c0 17.7-14.3 32-32 32H576c-11.8 0-22.2-6.4-27.7-16H463.4c-3.4 6.7-7.9 13.1-13.5 18.7c-17.1 17.1-40.8 23.8-63 20.1c-3.6 7.3-8.5 14.1-14.6 20.2c-27.3 27.3-70 30-100.4 8.1c-25.1 20.8-62.5 19.5-86-4.1L159 404l-7-7-35.6-35.6c-5.5-5.5-12.7-8.7-20.4-9.3C96 369.7 81.6 384 64 384H32c-17.7 0-32-14.3-32-32V144c0-8.8 7.2-16 16-16H56 96h19.8c2 0 3.9-.7 5.3-2l26.5-23.6C175.5 77.7 211.4 64 248.7 64H259c4.4 0 8.9 .2 13.2 .6zM544 320V176H496c-5.9 0-11.6-2.2-15.9-6.1l-36.9-32.8c-18.2-16.2-41.7-25.1-66.1-25.1c-25.4 0-49.8 9.7-68.3 27.1l-70.1 66.2c-10.3 9.8-10.1 26.3 .5 35.7c9.3 8.3 23.4 8.1 32.5-.3l71.9-66.4c9.7-9 24.9-8.4 33.9 1.4s8.4 24.9-1.4 33.9l-.8 .8 74.4 74.4c10 10 16.5 22.3 19.4 35.1H544zM64 336a16 16 0 1 0 -32 0 16 16 0 1 0 32 0zm528 16a16 16 0 1 0 0-32 16 16 0 1 0 0 32z"/></svg>');
        /* content: "CV"; */
        display: inline-block;
        width: 1rem;
        height: 1.5rem;
        margin-right: 1px;
        vertical-align: middle;
    }
</style>

<section class="widget p-2 relative">
    <input class="widget-toggle hidden absolute w-full" type="checkbox" />
    <div class="widget-title text-2xl">其他</div>
    <ul class="widget-list">
        <li>
            <i class="fa-solid fa-square-rss"></i>
            <a href="{% url 'blog:feed' %}" target="_blank">博客订阅</a>
        </li>
        <li>
            <i class="fa-solid fa-sitemap"></i>
            <a href="{% url 'sitemap' %}" target="_blank">站点地图</a>
        </li>
        <li>
            <i class="fa-solid fa-hand"></i>
            <a href="/resume/" target="_blank">个人简历</a>
        </li>
    </ul>
</section>

apps/blog/templates/blog/inclusions/_recent_posts.html
<section class="widget p-2 relative">
	<input class="widget-toggle hidden absolute w-full" type="checkbox" />
	<div class="widget-title text-2xl">最新</div>
	<ul class="widget-list">
		{% for post in recent_post_list %}
		<li>
			<i class="fa-solid fa-file-word"></i>
			<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
		</li>
		{% empty %}
		暂无文章！
		{% endfor %}
	</ul>
</section>
<div class="divider"></div>

apps/blog/templates/blog/inclusions/_tags.html
<section class="widget p-2 relative" id="tagsWidget">
	<input class="widget-toggle hidden absolute w-full" type="checkbox" />
	<div class="widget-title text-2xl">标签</div>
	<ul class="widget-list grid xl:grid-cols-2">
		{% for tag in tag_list %}
		<li data-level="{{tag.color_level}}" class="tag-item">
			<i class="fa-solid fa-tag"></i>
			<a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}
				<span>[{{ tag.num_posts }}]</span></a>
		</li>
		{% empty %}
		暂无标签！
		{% endfor %}
	</ul>
</section>
<script>
	if (/Android|iPhone/i.test(navigator.userAgent) ? true : false) {
		document.querySelector("#tagsWidget").querySelector(".widget-list").classList.add("grid-cols-2")
	}
	let textColorDark = ["dark:text-violet-300", "dark:text-violet-400", "dark:text-violet-500", "dark:text-violet-600", "dark:text-violet-800"]
	textColorDark = [...textColorDark].reverse();
	let textColorLight = ["text-pink-300", "text-pink-400", "text-pink-500", "text-pink-600", "text-pink-800"]
	document.querySelector("#tagsWidget").querySelector(".widget-list").querySelectorAll(".tag-item").forEach((item) => {
		item.classList.add(textColorLight[item.dataset.level - 1])
		item.classList.add(textColorDark[item.dataset.level - 1])
	})

</script>
<div class="divider"></div>