Morningstar/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.views.generic.base import TemplateView
from django.contrib.sitemaps.views import sitemap
from django.views.decorators.cache import cache_page
from rest_framework import routers
from rest_framework.documentation import include_docs_urls

from Morningstar.settings.common import CACHE_TIMEOUT
from Morningstar.settings.common import MEDIA_ROOT

from .views import dev, info, shortcut, tool
from .sitemaps import Sitemaps

router = routers.DefaultRouter()


infoUrls = [
    path("favicon.ico", cache_page(CACHE_TIMEOUT)(info.get_favicon), name="favicon"),
    path("qrcode/", cache_page(CACHE_TIMEOUT)(info.get_qrcode), name="qrcode"),
    path("me/", cache_page(CACHE_TIMEOUT)(info.me), name="me"),
    path("credits/", cache_page(CACHE_TIMEOUT)(info.credits), name="credits"),
    path(
        "sitemap.xml",
        cache_page(CACHE_TIMEOUT)(sitemap),
        {"sitemaps": Sitemaps},
        name="sitemap",
    ),
    path("dev/", dev.index, name="dev_index"),
    path(
        "shortcut/<slug:name>/",
        cache_page(CACHE_TIMEOUT)(shortcut.shortcut),
        name="shortcut",
    ),
    path(
        "robots.txt",
        cache_page(CACHE_TIMEOUT)(
            TemplateView.as_view(
                template_name="base/robots.txt", content_type="text/plain"
            )
        ),
    ),
]

authUrls = [
    path("get-image-captcha/", tool.get_image_captcha, name="get_image_captcha"),
    path("activate-by-email/", tool.activate_by_email, name="activate_by_email"),
    path(
        "send-phone-code/<slug:template>/", tool.send_phone_code, name="send_phone_code"
    ),
    path(
        "send-email-code/<slug:template>/", tool.send_email_code, name="send_email_code"
    ),
    path(
        "get-login-token/<slug:identity>/", tool.get_login_token, name="get_login_token"
    ),
    path("login-by-token/<str:token>/", tool.login_by_token, name="login_by_token"),
]


urlpatterns = (
    infoUrls
    + authUrls
    + [
        path("", include("blog.urls")),
        path("api/joke/", include("joke.urls")),
        path("lover/", include("lover.urls")),
        path("nav/", include("nav.urls")),
        path("proxy/", include("proxy.urls")),
        path("api/recognizer/", include("recognizer.urls")),
        path("rss/", include("rss.urls")),
        path("api/share/", include("share.urls")),
        # 调试
        path("debug/", include("debug_toolbar.urls")),
        # 媒体
        re_path(r"media/(?P<path>.*)$", serve, {"document_root": MEDIA_ROOT}),
        # 管理
        path("admin/", admin.site.urls, name="admin"),
        # restful api
        # path("api/", include(router.urls)), # TODO: 未来需要更规范的使用
        path("docs/", include_docs_urls(title="API文档", description="hiahiahia")),
    ]
)

apps/lover/urls.py
from django.urls import path
from Morningstar.settings.common import CACHE_TIMEOUT
from django.views.decorators.cache import cache_page
from . import views


app_name = "lover"
urlpatterns = [
    path("", views.index, name="index"),
    path("show/", views.show, name="show"),
    path("api/", views.api, name="api"),
    path("origin/", views.origin, name="origin"),
]

apps/lover/views.py
import os
import io
from PIL import Image
import numpy as np
import matplotlib
from random import randint
from pathlib import Path

from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, HttpRequest
from django.views.decorators.http import require_GET

from Morningstar.settings.common import MEDIA_ROOT


def __get_random_image():
    def get_image_list(image_dir: Path):
        image_list = [
            file
            for file in image_dir.glob("*")
            if file.is_file()
            and file.suffix.lower() in [".jpg", ".jpeg", ".png", ".gif", ".bmp"]
        ]
        return image_list

    image_list = get_image_list(MEDIA_ROOT / "lover" / "photo")
    image_num = len(image_list)
    image_ind = randint(0, image_num - 1)
    image = Image.open(image_list[image_ind])
    return image


def show(request: HttpRequest):
    image = __get_random_image()
    stream = io.BytesIO()
    image.save(stream, "png")
    return HttpResponse(stream.getvalue(), "image/png")


@require_GET
def api(request: HttpRequest):
    # 生成适配客户端的图片
    # 适配图片：1280x1706 600x800 3456x4608 1080x1440
    origin_image = __get_random_image()

    image_width = 384
    image_height = 512
    new_image = origin_image.resize((image_width, image_height))  # (width, height)

    # 数据处理
    array = np.asarray(new_image)  # (height,width,3)
    result = {"status": "success", "fills": []}

    for i in range(0, image_height - 4 + 1, 4):
        for j in range(0, image_width - 3 + 1, 3):
            r = array[i + 1, j + 1, 0] / 2 + array[i + 2, j + 1, 0] / 2
            g = array[i + 1, j + 1, 1] / 2 + array[i + 2, j + 1, 1] / 2
            b = array[i + 1, j + 1, 2] / 2 + array[i + 2, j + 1, 2] / 2
            rgb = matplotlib.colors.rgb2hex([r / 255, g / 255, b / 255])
            result["fills"].append(rgb)
    return JsonResponse(result)


def index(request: HttpRequest):
    return render(request, "lover/index.html")


def origin(request: HttpRequest):
    return redirect("http://www.koalastothemax.com/")

apps/lover/templates/lover/index.html
{% load compress %}
{% load matomo_tags %}
<!DOCTYPE html>
<html lang="en" data-theme="light">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=400">
	<title>Lover - 爱人相册</title>
	<meta name="description" content="随机展示爱人的照片">
	<link rel="icon" href="{% static 'lover/img/favicon.ico' %}">
	<link rel="apple-touch-icon" href="{% static 'lover/img/favicon.png' %}">
	{% compress css %}
	<link rel="stylesheet" href="{% static 'lover/css/style.css' %}">
	{% endcompress %}
	<link rel="stylesheet" href="{% static 'node_modules/animate.css/animate.min.css' %}">
	<link rel="stylesheet" href="{% static 'node_modules/pace-js/pace-theme-default.min.css' %}">
	<script src="{% static 'node_modules/pace-js/pace.min.js' %}"></script>
	{% tracking_code %}
</head>

<body class="flex flex-col justify-between items-center overflow-hidden fixed w-screen"
	style="height: -webkit-fill-available;">
	<header class="animate__animated animate__backInDown text-pink-300 text-2xl pt-6">
		谨以此页献给我的爱人FQL~
	</header>
	<main id="wrapper" class="flex-1 flex justify-center items-center">
		<div id="prompt" class="font-bold text-center p-7 rounded-3xl text-6xl border-8 border-double border-rose-600">
			loading...
		</div>
	</main>
	<footer class="pb-2">
		<div class="text-center">
			<div id="runtime_span"></div>
			<div id="copyright">
				<span>© 2022
					<a href="{% url 'me' %}" class="font-bold" style="font-family: Lora">Henry Ji</a>
				</span>
				<span class="brightness-0">/</span>
				<span>License: <a href="https://www.gnu.org/licenses/agpl-3.0.en.html"
						class="font-bold">AGPLv3</a></span>
				<span class="brightness-0">/</span>
				<span>Powered by <a href="https://www.djangoproject.com/" class="font-bold">Django</a></span>
			</div>
		</div>
		{% compress js %}
		<script src="{% static 'base/js/runtime.js' %}"></script>
		{% endcompress %}
	</footer>

</body>
<script data-href="https://github.com/HenryJi529/OpenMorningstar"
	src="{% static 'node_modules/github-corners/dist/embed.min.js' %}"></script>
{% compress js %}
<script src="{% static 'lover/js/app.js' %}"></script>
{% endcompress %}
<!-- 初始化 -->
<script>
	const isMobile = /Android|iPhone/i.test(navigator.userAgent) ? true : false;
	const api = "{% url 'lover:api' %}" + `?isMobile=${isMobile}`;
	let trigger = isMobile ? "touchenter" : "mousemove";
	let fills;
	let maxLevel = 7;
	let svg;

	fetch(api).then(res => res.json()).
		then(data => {
			// 暂存数据
			fills = data["fills"].map(x => transformColorHex2Dec(x));

			// 初始化面板
			const wrapper = document.querySelector("#wrapper");
			const promptElement = document.querySelector("#prompt");
			wrapper.removeChild(promptElement);

			// 创建svg图形
			svg = document.createElementNS("http://www.w3.org/2000/svg", 'svg')
			svg.setAttribute("width", 2 ** maxLevel * 3)
			svg.setAttribute("height", 2 ** maxLevel * 4)
			wrapper.appendChild(svg)

			// 创建touchEnter事件
			let touchEnterEvent = new Event("touchenter");
			const elementContains = (parent, child) => parent !== child && parent.contains(child);
			document.dispatchEvent(touchEnterEvent);
			document.addEventListener("touchmove", (e) => {
				let el = document.elementFromPoint(e.touches[0].clientX, e.touches[0].clientY);
				if (!el) {
					return;
				} else {
					if (elementContains(svg, el)) {
						el.dispatchEvent(touchEnterEvent);
					};
				}
			}
			)

			// 创建基础椭圆
			let initialCx = 2 ** maxLevel * 3 / 2;
			let initialCy = 2 ** maxLevel * 4 / 2;
			let initialLevel = maxLevel;
			let initialFill = getCurrentFill(initialCx, initialCy, initialLevel);
			let initialRx = getCurrentRx(initialLevel);
			let initialRy = getCurrentRy(initialLevel);
			let initialEllipse = createEllipse(initialCx, initialCy, initialRx, initialRy, initialFill, initialLevel);

			// 自动完成功能
			const autoCheck = setInterval(() => {
				console.log(`已完成数量: ${svg.childNodes.length}`);
				if (svg.childNodes.length >= 1500) {
					clearInterval(autoCheck);
					autoFinish();
				}
			}, 1000);
		})
</script>

</html>